
export const leadTypes = [
  {
    id: "alto",
    label: "Excellent Prospect",
    description: "No website but has contact info",
    color: "bg-green-100 text-green-800",
  },
  {
    id: "medio",
    label: "Good Lead",
    description: "Poor website (Lighthouse <40) with contact info",
    color: "bg-blue-100 text-blue-800",
  },
  {
    id: "bajo",
    label: "Medium Lead",
    description: "Average website (Lighthouse 40-79) with contact info",
    color: "bg-yellow-100 text-yellow-800",
  },
  {
    id: "desconocido",
    label: "unknown",
    description: "the data provided by pagespeed is not enough to determine the lead type",
    color: "bg-purple-100 text-purple-800",
  },
]


export const mockTableLeads = [
  {
    id: "1",
    businessName: "Sweet Dreams Bakery",
    category: "Bakery",
    phone: "(555) 123-4567",
    email: "info@sweetdreamsbakery.com",
    address: "123 Main St, Atlanta, GA 30309",
    leadScore: 95,
    leadType: "excellent",
    isInZoho: true,
    dateAdded: "2024-01-15",
    city: "Atlanta",
    state: "GA",
    source: "google-maps",
    googleMapsListing: true,
  },
  {
    id: "2",
    businessName: "Downtown Dental Care",
    category: "Dentist",
    website: "https://downtowndental.com",
    phone: "(555) 987-6543",
    address: "456 Oak Ave, Atlanta, GA 30308",
    lighthouseScore: 35,
    leadScore: 82,
    leadType: "good",
    isInZoho: false,
    dateAdded: "2024-01-14",
    city: "Atlanta",
    state: "GA",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 3,
  },
  {
    id: "3",
    businessName: "Bella Vista Restaurant",
    category: "Restaurant",
    website: "https://bellavista.com",
    phone: "(555) 456-7890",
    email: "contact@bellavista.com",
    address: "789 Pine St, Atlanta, GA 30307",
    lighthouseScore: 65,
    leadScore: 71,
    leadType: "medium",
    isInZoho: true,
    dateAdded: "2024-01-13",
    city: "Atlanta",
    state: "GA",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 1,
  },
]
