export const businessTypes = [
  { id: "bakery", name: "Bakery", category: "Food & Beverage" },
  { id: "dentist", name: "Dentist", category: "Healthcare" },
  { id: "restaurant", name: "Restaurant", category: "Food & Beverage" },
  { id: "salon", name: "Hair Salon", category: "Beauty & Wellness" },
  { id: "gym", name: "Gym", category: "Fitness" },
  { id: "plumber", name: "Plumber", category: "Home Services" },
  { id: "lawyer", name: "Lawyer", category: "Professional Services" },
  { id: "accountant", name: "Accountant", category: "Professional Services" },
  { id: "mechanic", name: "Auto Mechanic", category: "Automotive" },
  { id: "florist", name: "Florist", category: "Retail" },
  { id: "photographer", name: "Photographer", category: "Creative Services" },
  { id: "contractor", name: "Contractor", category: "Construction" },
]

export const cities = [
  { id: "atlanta", name: "Atlanta", state: "GA" },
  { id: "austin", name: "Austin", state: "TX" },
  { id: "boston", name: "Boston", state: "MA" },
  { id: "chicago", name: "Chicago", state: "IL" },
  { id: "dallas", name: "Dallas", state: "TX" },
  { id: "denver", name: "Denver", state: "CO" },
  { id: "houston", name: "Houston", state: "TX" },
  { id: "los-angeles", name: "Los Angeles", state: "CA" },
  { id: "miami", name: "Miami", state: "FL" },
  { id: "new-york", name: "New York", state: "NY" },
  { id: "philadelphia", name: "Philadelphia", state: "PA" },
  { id: "phoenix", name: "Phoenix", state: "AZ" },
  { id: "san-francisco", name: "San Francisco", state: "CA" },
  { id: "seattle", name: "Seattle", state: "WA" },
]

export const leadTypes = [
  {
    id: "excellent",
    label: "Excellent Prospect",
    description: "No website but has contact info",
    color: "bg-green-100 text-green-800",
  },
  {
    id: "good",
    label: "Good Lead",
    description: "Poor website (Lighthouse <40) with contact info",
    color: "bg-blue-100 text-blue-800",
  },
  {
    id: "medium",
    label: "Medium Lead",
    description: "Average website (Lighthouse 40-79) with contact info",
    color: "bg-yellow-100 text-yellow-800",
  },
  {
    id: "poor",
    label: "Poor Lead",
    description: "Good website (Lighthouse 80+) with contact info",
    color: "bg-purple-100 text-purple-800",
  },
  {
    id: "research-needed",
    label: "Research Needed",
    description: "No website and no contact info",
    color: "bg-gray-100 text-gray-800",
  },
]

export const mockLeads = [
  {
    id: "1",
    businessName: "Sweet Dreams Bakery",
    category: "Bakery",
    phone: "(555) 123-4567",
    email: "info@sweetdreamsbakery.com",
    address: "123 Main St, Atlanta, GA 30309",
    leadScore: 95,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 45,
      factors: {
        googleMyBusiness: 80,
        localKeywords: 30,
        reviews: 60,
        citations: 40,
        websiteOptimization: 0,
      },
      recommendations: ["Create a professional website", "Optimize for local keywords", "Encourage customer reviews"],
    },
  },
  {
    id: "2",
    businessName: "Downtown Dental Care",
    category: "Dentist",
    website: "https://downtowndental.com",
    phone: "(555) 987-6543",
    address: "456 Oak Ave, Atlanta, GA 30308",
    lighthouseScore: 35,
    leadScore: 82,
    leadType: "good",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 3,
    searchSnippet: {
      title: "Downtown Dental Care - Professional Dental Services",
      description:
        "Comprehensive dental care in downtown Atlanta. Emergency appointments available. Call today for your consultation.",
      url: "https://downtowndental.com",
      displayUrl: "downtowndental.com",
    },
    localSEOScore: {
      overallScore: 72,
      factors: {
        googleMyBusiness: 85,
        localKeywords: 70,
        reviews: 75,
        citations: 65,
        websiteOptimization: 45,
      },
      recommendations: ["Improve website loading speed", "Add more local service pages", "Optimize for mobile users"],
    },
  },
  {
    id: "3",
    businessName: "Bella Vista Restaurant",
    category: "Restaurant",
    website: "https://bellavista.com",
    phone: "(555) 456-7890",
    email: "contact@bellavista.com",
    address: "789 Pine St, Atlanta, GA 30307",
    lighthouseScore: 65,
    leadScore: 71,
    leadType: "medium",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 1,
    searchSnippet: {
      title: "Bella Vista Restaurant - Authentic Italian Cuisine",
      description:
        "Experience authentic Italian dining in the heart of Atlanta. Fresh ingredients, traditional recipes, and warm atmosphere.",
      url: "https://bellavista.com",
      displayUrl: "bellavista.com",
    },
    localSEOScore: {
      overallScore: 78,
      factors: {
        googleMyBusiness: 90,
        localKeywords: 75,
        reviews: 85,
        citations: 70,
        websiteOptimization: 70,
      },
      recommendations: [
        "Add online ordering system",
        "Create location-specific landing pages",
        "Improve schema markup",
      ],
    },
  },
  {
    id: "4",
    businessName: "Elite Hair Studio",
    category: "Hair Salon",
    website: "https://elitehairstudio.com",
    phone: "(555) 321-0987",
    address: "321 Elm St, Atlanta, GA 30306",
    lighthouseScore: 88,
    leadScore: 45,
    leadType: "poor",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 85,
      factors: {
        googleMyBusiness: 95,
        localKeywords: 80,
        reviews: 90,
        citations: 85,
        websiteOptimization: 90,
      },
      recommendations: [
        "Maintain current SEO performance",
        "Consider expanding service keywords",
        "Monitor competitor activities",
      ],
    },
  },
  {
    id: "5",
    businessName: "City Fitness Center",
    category: "Gym",
    address: "654 Maple Ave, Atlanta, GA 30305",
    leadScore: 25,
    leadType: "research-needed",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 25,
      factors: {
        googleMyBusiness: 60,
        localKeywords: 10,
        reviews: 30,
        citations: 20,
        websiteOptimization: 0,
      },
      recommendations: [
        "Create a professional website",
        "Set up Google My Business properly",
        "Start collecting customer reviews",
        "Build local citations",
      ],
    },
  },
]

export const mockTableLeads = [
  {
    id: "1",
    businessName: "Sweet Dreams Bakery",
    category: "Bakery",
    phone: "(555) 123-4567",
    email: "info@sweetdreamsbakery.com",
    address: "123 Main St, Atlanta, GA 30309",
    leadScore: 95,
    leadType: "excellent",
    isInZoho: true,
    dateAdded: "2024-01-15",
    city: "Atlanta",
    state: "GA",
    source: "google-maps",
    googleMapsListing: true,
  },
  {
    id: "2",
    businessName: "Downtown Dental Care",
    category: "Dentist",
    website: "https://downtowndental.com",
    phone: "(555) 987-6543",
    address: "456 Oak Ave, Atlanta, GA 30308",
    lighthouseScore: 35,
    leadScore: 82,
    leadType: "good",
    isInZoho: false,
    dateAdded: "2024-01-14",
    city: "Atlanta",
    state: "GA",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 3,
  },
  {
    id: "3",
    businessName: "Bella Vista Restaurant",
    category: "Restaurant",
    website: "https://bellavista.com",
    phone: "(555) 456-7890",
    email: "contact@bellavista.com",
    address: "789 Pine St, Atlanta, GA 30307",
    lighthouseScore: 65,
    leadScore: 71,
    leadType: "medium",
    isInZoho: true,
    dateAdded: "2024-01-13",
    city: "Atlanta",
    state: "GA",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 1,
  },
]
