import type {
  BusinessType,
  City,
  Lead,
  SearchResult,
  LeadType,
  LeadTableItem,
  SearchTrendData,
  CompetitorAnalysis,
} from "./types"

export const mockTrendData: SearchTrendData = {
  searchVolume: 12500,
  trend: "increasing",
  seasonality: "Higher demand in Q4 (holiday season)",
  competitionLevel: "medium",
}

export const mockCompetitorAnalysis: CompetitorAnalysis = {
  totalCompetitors: 47,
  topCompetitors: [
    { name: "Sweet Treats Bakery", ranking: 1, hasWebsite: true, estimatedTraffic: "2.5K/month" },
    { name: "Corner Bakehouse", ranking: 2, hasWebsite: false },
    { name: "Artisan Bread Co", ranking: 3, hasWebsite: true, estimatedTraffic: "1.8K/month" },
    { name: "Daily Bread Bakery", ranking: 4, hasWebsite: true, estimatedTraffic: "950/month" },
    { name: "Fresh Start Bakery", ranking: 5, hasWebsite: false },
  ],
  marketSaturation: "medium",
}

export const businessTypes: BusinessType[] = [
  { id: "bakery", name: "Bakery", category: "Food & Beverage" },
  { id: "dentist", name: "Dentist", category: "Healthcare" },
  { id: "restaurant", name: "Restaurant", category: "Food & Beverage" },
  { id: "salon", name: "Hair Salon", category: "Beauty & Wellness" },
  { id: "gym", name: "Gym", category: "Fitness" },
  { id: "plumber", name: "Plumber", category: "Home Services" },
  { id: "lawyer", name: "Lawyer", category: "Professional Services" },
  { id: "accountant", name: "Accountant", category: "Professional Services" },
  { id: "mechanic", name: "Auto Mechanic", category: "Automotive" },
  { id: "florist", name: "Florist", category: "Retail" },
  { id: "photographer", name: "Photographer", category: "Creative Services" },
  { id: "contractor", name: "Contractor", category: "Construction" },
]

export const cities: City[] = [
  { id: "atlanta", name: "Atlanta", state: "GA" },
  { id: "austin", name: "Austin", state: "TX" },
  { id: "boston", name: "Boston", state: "MA" },
  { id: "chicago", name: "Chicago", state: "IL" },
  { id: "dallas", name: "Dallas", state: "TX" },
  { id: "denver", name: "Denver", state: "CO" },
  { id: "houston", name: "Houston", state: "TX" },
  { id: "los-angeles", name: "Los Angeles", state: "CA" },
  { id: "miami", name: "Miami", state: "FL" },
  { id: "new-york", name: "New York", state: "NY" },
  { id: "philadelphia", name: "Philadelphia", state: "PA" },
  { id: "phoenix", name: "Phoenix", state: "AZ" },
  { id: "san-francisco", name: "San Francisco", state: "CA" },
  { id: "seattle", name: "Seattle", state: "WA" },
]

export const leadTypes: LeadType[] = [
  {
    id: "excellent",
    label: "Excellent Prospect",
    description: "No website but has contact info",
    color: "bg-green-100 text-green-800",
  },
  {
    id: "good",
    label: "Good Lead",
    description: "Poor website (Lighthouse <40) with contact info",
    color: "bg-blue-100 text-blue-800",
  },
  {
    id: "medium",
    label: "Medium Lead",
    description: "Average website (Lighthouse 40-79) with contact info",
    color: "bg-yellow-100 text-yellow-800",
  },
  {
    id: "poor",
    label: "Poor Lead",
    description: "Good website (Lighthouse 80+) with contact info",
    color: "bg-purple-100 text-purple-800",
  },
  {
    id: "research-needed",
    label: "Research Needed",
    description: "No website and no contact info",
    color: "bg-gray-100 text-gray-800",
  },
]

export const mockLeads: Lead[] = [
  {
    id: "1",
    businessName: "Sweet Dreams Bakery",
    category: "Bakery",
    phone: "(555) 123-4567",
    email: "info@sweetdreamsbakery.com",
    address: "123 Main St, Atlanta, GA 30309",
    leadScore: 95,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 45,
      factors: {
        googleMyBusiness: 80,
        localKeywords: 30,
        reviews: 60,
        citations: 40,
        websiteOptimization: 0,
      },
      recommendations: ["Create a professional website", "Optimize for local keywords", "Encourage customer reviews"],
    },
  },
  {
    id: "2",
    businessName: "Downtown Dental Care",
    category: "Dentist",
    website: "https://downtowndental.com",
    phone: "(555) 987-6543",
    address: "456 Oak Ave, Atlanta, GA 30308",
    lighthouseScore: 35,
    leadScore: 82,
    leadType: "good",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 3,
    searchSnippet: {
      title: "Downtown Dental Care - Professional Dental Services",
      description:
        "Comprehensive dental care in downtown Atlanta. Emergency appointments available. Call today for your consultation.",
      url: "https://downtowndental.com",
      displayUrl: "downtowndental.com",
    },
    localSEOScore: {
      overallScore: 72,
      factors: {
        googleMyBusiness: 85,
        localKeywords: 70,
        reviews: 75,
        citations: 65,
        websiteOptimization: 45,
      },
      recommendations: ["Improve website loading speed", "Add more local service pages", "Optimize for mobile users"],
    },
  },
  {
    id: "3",
    businessName: "Bella Vista Restaurant",
    category: "Restaurant",
    website: "https://bellavista.com",
    phone: "(555) 456-7890",
    email: "contact@bellavista.com",
    address: "789 Pine St, Atlanta, GA 30307",
    lighthouseScore: 65,
    leadScore: 71,
    leadType: "medium",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 1,
    searchSnippet: {
      title: "Bella Vista Restaurant - Authentic Italian Cuisine",
      description:
        "Experience authentic Italian dining in the heart of Atlanta. Fresh ingredients, traditional recipes, and warm atmosphere.",
      url: "https://bellavista.com",
      displayUrl: "bellavista.com",
    },
    localSEOScore: {
      overallScore: 78,
      factors: {
        googleMyBusiness: 90,
        localKeywords: 75,
        reviews: 85,
        citations: 70,
        websiteOptimization: 70,
      },
      recommendations: [
        "Add online ordering system",
        "Create location-specific landing pages",
        "Improve schema markup",
      ],
    },
  },
  {
    id: "4",
    businessName: "Elite Hair Studio",
    category: "Hair Salon",
    website: "https://elitehairstudio.com",
    phone: "(555) 321-0987",
    address: "321 Elm St, Atlanta, GA 30306",
    lighthouseScore: 88,
    leadScore: 45,
    leadType: "poor",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 85,
      factors: {
        googleMyBusiness: 95,
        localKeywords: 80,
        reviews: 90,
        citations: 85,
        websiteOptimization: 90,
      },
      recommendations: [
        "Maintain current SEO performance",
        "Consider expanding service keywords",
        "Monitor competitor activities",
      ],
    },
  },
  {
    id: "5",
    businessName: "City Fitness Center",
    category: "Gym",
    address: "654 Maple Ave, Atlanta, GA 30305",
    leadScore: 25,
    leadType: "research-needed",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 25,
      factors: {
        googleMyBusiness: 60,
        localKeywords: 10,
        reviews: 30,
        citations: 20,
        websiteOptimization: 0,
      },
      recommendations: [
        "Create a professional website",
        "Set up Google My Business properly",
        "Start collecting customer reviews",
        "Build local citations",
      ],
    },
  },
  {
    id: "6",
    businessName: "Perfect Plumbing Solutions",
    category: "Plumber",
    phone: "(555) 789-0123",
    address: "987 Water St, Atlanta, GA 30304",
    leadScore: 88,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 55,
      factors: {
        googleMyBusiness: 75,
        localKeywords: 45,
        reviews: 70,
        citations: 50,
        websiteOptimization: 0,
      },
      recommendations: [
        "Build a professional website",
        "Target emergency plumbing keywords",
        "Expand service area coverage",
      ],
    },
  },
  {
    id: "7",
    businessName: "Atlanta Artisan Bakery",
    category: "Bakery",
    website: "https://atlantaartisan.com",
    phone: "(555) 111-2222",
    email: "hello@atlantaartisan.com",
    address: "555 Creative St, Atlanta, GA 30310",
    lighthouseScore: 72,
    leadScore: 78,
    leadType: "medium",
    source: "google-search",
    googleSearchRanking: 2,
    searchSnippet: {
      title: "Atlanta Artisan Bakery - Handcrafted Breads & Pastries",
      description:
        "Artisan bakery specializing in handcrafted breads, pastries, and custom cakes. Made fresh daily with organic ingredients.",
      url: "https://atlantaartisan.com",
      displayUrl: "atlantaartisan.com",
    },
    localSEOScore: {
      overallScore: 68,
      factors: {
        googleMyBusiness: 70,
        localKeywords: 65,
        reviews: 75,
        citations: 60,
        websiteOptimization: 70,
      },
      recommendations: ["Improve website speed", "Add more local content", "Optimize for voice search"],
    },
  },
  {
    id: "8",
    businessName: "Neighborhood Baking Co",
    category: "Bakery",
    website: "https://neighborhoodbaking.com",
    address: "777 Community Ave, Atlanta, GA 30311",
    lighthouseScore: 45,
    leadScore: 65,
    leadType: "good",
    source: "google-search",
    googleSearchRanking: 5,
    searchSnippet: {
      title: "Neighborhood Baking Co - Community Bakery",
      description:
        "Your neighborhood bakery serving fresh bread, cookies, and cakes. Family-owned and operated since 2015.",
      url: "https://neighborhoodbaking.com",
      displayUrl: "neighborhoodbaking.com",
    },
    localSEOScore: {
      overallScore: 52,
      factors: {
        googleMyBusiness: 60,
        localKeywords: 50,
        reviews: 55,
        citations: 45,
        websiteOptimization: 50,
      },
      recommendations: ["Improve website performance", "Add contact information", "Build more local backlinks"],
    },
  },
  // Additional 30+ leads
  {
    id: "9",
    businessName: "Sunrise Dental Group",
    category: "Dentist",
    phone: "(555) 234-5678",
    email: "appointments@sunrisedental.com",
    address: "1234 Peachtree St, Atlanta, GA 30309",
    leadScore: 92,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 42,
      factors: {
        googleMyBusiness: 85,
        localKeywords: 25,
        reviews: 65,
        citations: 35,
        websiteOptimization: 0,
      },
      recommendations: ["Create a professional website", "Optimize for dental keywords", "Build local citations"],
    },
  },
  {
    id: "10",
    businessName: "The Burger Joint",
    category: "Restaurant",
    website: "https://burgerjoint.com",
    phone: "(555) 345-6789",
    address: "567 Broad St, Atlanta, GA 30308",
    lighthouseScore: 38,
    leadScore: 79,
    leadType: "good",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 4,
    searchSnippet: {
      title: "The Burger Joint - Gourmet Burgers & Fries",
      description: "Fresh, locally-sourced burgers and hand-cut fries. Open late for your convenience.",
      url: "https://burgerjoint.com",
      displayUrl: "burgerjoint.com",
    },
    localSEOScore: {
      overallScore: 58,
      factors: {
        googleMyBusiness: 75,
        localKeywords: 55,
        reviews: 70,
        citations: 50,
        websiteOptimization: 40,
      },
      recommendations: ["Improve website speed", "Add online ordering", "Optimize for mobile"],
    },
  },
  {
    id: "11",
    businessName: "Glamour Nails & Spa",
    category: "Hair Salon",
    phone: "(555) 456-7890",
    address: "890 Midtown Ave, Atlanta, GA 30307",
    leadScore: 87,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 48,
      factors: {
        googleMyBusiness: 80,
        localKeywords: 35,
        reviews: 60,
        citations: 40,
        websiteOptimization: 0,
      },
      recommendations: ["Build a website", "Target nail salon keywords", "Encourage more reviews"],
    },
  },
  {
    id: "12",
    businessName: "Iron Gym Fitness",
    category: "Gym",
    website: "https://irongymfitness.com",
    phone: "(555) 567-8901",
    email: "info@irongymfitness.com",
    address: "432 Fitness Blvd, Atlanta, GA 30306",
    lighthouseScore: 62,
    leadScore: 73,
    leadType: "medium",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 2,
    searchSnippet: {
      title: "Iron Gym Fitness - 24/7 Fitness Center",
      description: "State-of-the-art equipment, personal training, and group classes. Open 24/7 for your convenience.",
      url: "https://irongymfitness.com",
      displayUrl: "irongymfitness.com",
    },
    localSEOScore: {
      overallScore: 65,
      factors: {
        googleMyBusiness: 80,
        localKeywords: 60,
        reviews: 70,
        citations: 55,
        websiteOptimization: 65,
      },
      recommendations: ["Improve website performance", "Add class schedules", "Optimize for local searches"],
    },
  },
  {
    id: "13",
    businessName: "Quick Fix Plumbing",
    category: "Plumber",
    website: "https://quickfixplumbing.com",
    phone: "(555) 678-9012",
    address: "765 Service Rd, Atlanta, GA 30305",
    lighthouseScore: 41,
    leadScore: 81,
    leadType: "good",
    source: "google-search",
    googleSearchRanking: 1,
    searchSnippet: {
      title: "Quick Fix Plumbing - Emergency Plumbing Services",
      description: "24/7 emergency plumbing services. Licensed and insured. Call now for immediate assistance.",
      url: "https://quickfixplumbing.com",
      displayUrl: "quickfixplumbing.com",
    },
    localSEOScore: {
      overallScore: 62,
      factors: {
        googleMyBusiness: 75,
        localKeywords: 65,
        reviews: 60,
        citations: 55,
        websiteOptimization: 45,
      },
      recommendations: ["Improve website speed", "Add service area pages", "Build more citations"],
    },
  },
  {
    id: "14",
    businessName: "Smith & Associates Law",
    category: "Lawyer",
    website: "https://smithlawfirm.com",
    phone: "(555) 789-0123",
    email: "contact@smithlawfirm.com",
    address: "321 Legal Plaza, Atlanta, GA 30304",
    lighthouseScore: 85,
    leadScore: 48,
    leadType: "poor",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 3,
    searchSnippet: {
      title: "Smith & Associates Law - Personal Injury Attorneys",
      description: "Experienced personal injury lawyers fighting for your rights. Free consultation available.",
      url: "https://smithlawfirm.com",
      displayUrl: "smithlawfirm.com",
    },
    localSEOScore: {
      overallScore: 82,
      factors: {
        googleMyBusiness: 90,
        localKeywords: 85,
        reviews: 80,
        citations: 75,
        websiteOptimization: 85,
      },
      recommendations: ["Maintain current performance", "Expand practice area content", "Monitor competitors"],
    },
  },
  {
    id: "15",
    businessName: "Precision Accounting Services",
    category: "Accountant",
    phone: "(555) 890-1234",
    email: "info@precisionaccounting.com",
    address: "654 Business Center, Atlanta, GA 30310",
    leadScore: 89,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 44,
      factors: {
        googleMyBusiness: 75,
        localKeywords: 30,
        reviews: 55,
        citations: 40,
        websiteOptimization: 0,
      },
      recommendations: ["Create a professional website", "Target tax preparation keywords", "Build online presence"],
    },
  },
  {
    id: "16",
    businessName: "AutoCare Mechanics",
    category: "Auto Mechanic",
    website: "https://autocaremechanics.com",
    phone: "(555) 901-2345",
    address: "987 Auto Row, Atlanta, GA 30311",
    lighthouseScore: 55,
    leadScore: 76,
    leadType: "medium",
    source: "google-search",
    googleSearchRanking: 6,
    searchSnippet: {
      title: "AutoCare Mechanics - Full Service Auto Repair",
      description: "Complete automotive repair services. ASE certified technicians. Free estimates on all repairs.",
      url: "https://autocaremechanics.com",
      displayUrl: "autocaremechanics.com",
    },
    localSEOScore: {
      overallScore: 61,
      factors: {
        googleMyBusiness: 70,
        localKeywords: 60,
        reviews: 65,
        citations: 50,
        websiteOptimization: 60,
      },
      recommendations: ["Improve website performance", "Add service descriptions", "Encourage customer reviews"],
    },
  },
  {
    id: "17",
    businessName: "Bloom Florist",
    category: "Florist",
    phone: "(555) 012-3456",
    address: "123 Garden Way, Atlanta, GA 30312",
    leadScore: 84,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 46,
      factors: {
        googleMyBusiness: 80,
        localKeywords: 35,
        reviews: 60,
        citations: 35,
        websiteOptimization: 0,
      },
      recommendations: ["Build an e-commerce website", "Optimize for wedding flowers", "Expand online presence"],
    },
  },
  {
    id: "18",
    businessName: "Capture Moments Photography",
    category: "Photographer",
    website: "https://capturemoments.com",
    phone: "(555) 123-4567",
    email: "hello@capturemoments.com",
    address: "456 Studio Lane, Atlanta, GA 30313",
    lighthouseScore: 78,
    leadScore: 69,
    leadType: "medium",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 2,
    searchSnippet: {
      title: "Capture Moments Photography - Wedding & Portrait Photography",
      description: "Professional wedding and portrait photography. Capturing your special moments with artistic flair.",
      url: "https://capturemoments.com",
      displayUrl: "capturemoments.com",
    },
    localSEOScore: {
      overallScore: 72,
      factors: {
        googleMyBusiness: 85,
        localKeywords: 70,
        reviews: 75,
        citations: 65,
        websiteOptimization: 75,
      },
      recommendations: ["Add more portfolio content", "Optimize for wedding keywords", "Improve loading speed"],
    },
  },
  {
    id: "19",
    businessName: "BuildRight Construction",
    category: "Contractor",
    phone: "(555) 234-5678",
    address: "789 Construction Ave, Atlanta, GA 30314",
    leadScore: 91,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 41,
      factors: {
        googleMyBusiness: 75,
        localKeywords: 25,
        reviews: 50,
        citations: 35,
        websiteOptimization: 0,
      },
      recommendations: ["Create a portfolio website", "Target home renovation keywords", "Build contractor citations"],
    },
  },
  {
    id: "20",
    businessName: "Fresh Bites Cafe",
    category: "Restaurant",
    website: "https://freshbitescafe.com",
    address: "321 Coffee St, Austin, TX 78701",
    lighthouseScore: 43,
    leadScore: 67,
    leadType: "good",
    source: "google-search",
    googleSearchRanking: 7,
    searchSnippet: {
      title: "Fresh Bites Cafe - Organic Coffee & Healthy Meals",
      description: "Organic coffee, fresh salads, and healthy meal options. Perfect for breakfast and lunch.",
      url: "https://freshbitescafe.com",
      displayUrl: "freshbitescafe.com",
    },
    localSEOScore: {
      overallScore: 54,
      factors: {
        googleMyBusiness: 65,
        localKeywords: 50,
        reviews: 60,
        citations: 45,
        websiteOptimization: 45,
      },
      recommendations: ["Improve website performance", "Add online menu", "Optimize for breakfast keywords"],
    },
  },
  {
    id: "21",
    businessName: "Austin Family Dentistry",
    category: "Dentist",
    website: "https://austinfamilydentistry.com",
    phone: "(512) 345-6789",
    email: "info@austinfamilydentistry.com",
    address: "654 Dental Drive, Austin, TX 78702",
    lighthouseScore: 89,
    leadScore: 52,
    leadType: "poor",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 1,
    searchSnippet: {
      title: "Austin Family Dentistry - Comprehensive Dental Care",
      description: "Complete family dental services including cleanings, fillings, and cosmetic dentistry.",
      url: "https://austinfamilydentistry.com",
      displayUrl: "austinfamilydentistry.com",
    },
    localSEOScore: {
      overallScore: 88,
      factors: {
        googleMyBusiness: 95,
        localKeywords: 85,
        reviews: 90,
        citations: 85,
        websiteOptimization: 90,
      },
      recommendations: ["Maintain excellent performance", "Consider expanding services", "Monitor local competition"],
    },
  },
  {
    id: "22",
    businessName: "Trendy Cuts Salon",
    category: "Hair Salon",
    phone: "(512) 456-7890",
    address: "987 Style Street, Austin, TX 78703",
    leadScore: 86,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 47,
      factors: {
        googleMyBusiness: 80,
        localKeywords: 35,
        reviews: 65,
        citations: 40,
        websiteOptimization: 0,
      },
      recommendations: ["Build a booking website", "Target hair styling keywords", "Showcase portfolio online"],
    },
  },
  {
    id: "23",
    businessName: "FitZone Gym",
    category: "Gym",
    website: "https://fitzonegym.com",
    address: "432 Workout Way, Austin, TX 78704",
    lighthouseScore: 36,
    leadScore: 58,
    leadType: "good",
    source: "google-search",
    googleSearchRanking: 8,
    searchSnippet: {
      title: "FitZone Gym - Modern Fitness Facility",
      description: "Modern gym with latest equipment, group classes, and personal training services.",
      url: "https://fitzonegym.com",
      displayUrl: "fitzonegym.com",
    },
    localSEOScore: {
      overallScore: 51,
      factors: {
        googleMyBusiness: 60,
        localKeywords: 45,
        reviews: 55,
        citations: 40,
        websiteOptimization: 40,
      },
      recommendations: ["Improve website speed", "Add membership information", "Build local fitness citations"],
    },
  },
  {
    id: "24",
    businessName: "Reliable Plumbing Co",
    category: "Plumber",
    phone: "(512) 567-8901",
    email: "service@reliableplumbing.com",
    address: "765 Pipe Lane, Austin, TX 78705",
    leadScore: 93,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 43,
      factors: {
        googleMyBusiness: 85,
        localKeywords: 30,
        reviews: 60,
        citations: 35,
        websiteOptimization: 0,
      },
      recommendations: ["Create a service website", "Target emergency plumbing", "Build contractor directories"],
    },
  },
  {
    id: "25",
    businessName: "Legal Eagles Law Firm",
    category: "Lawyer",
    website: "https://legaleagleslaw.com",
    phone: "(512) 678-9012",
    address: "123 Justice Blvd, Austin, TX 78706",
    lighthouseScore: 92,
    leadScore: 44,
    leadType: "poor",
    source: "google-search",
    googleSearchRanking: 2,
    searchSnippet: {
      title: "Legal Eagles Law Firm - Criminal Defense Attorneys",
      description: "Experienced criminal defense lawyers. Protecting your rights with aggressive representation.",
      url: "https://legaleagleslaw.com",
      displayUrl: "legaleagleslaw.com",
    },
    localSEOScore: {
      overallScore: 91,
      factors: {
        googleMyBusiness: 95,
        localKeywords: 90,
        reviews: 90,
        citations: 90,
        websiteOptimization: 95,
      },
      recommendations: ["Excellent performance", "Continue content marketing", "Monitor SERP positions"],
    },
  },
  {
    id: "26",
    businessName: "Numbers Plus Accounting",
    category: "Accountant",
    website: "https://numbersplusaccounting.com",
    address: "456 Finance St, Austin, TX 78707",
    lighthouseScore: 67,
    leadScore: 72,
    leadType: "medium",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 4,
    searchSnippet: {
      title: "Numbers Plus Accounting - Tax Preparation & Bookkeeping",
      description: "Professional tax preparation and bookkeeping services for individuals and small businesses.",
      url: "https://numbersplusaccounting.com",
      displayUrl: "numbersplusaccounting.com",
    },
    localSEOScore: {
      overallScore: 69,
      factors: {
        googleMyBusiness: 80,
        localKeywords: 65,
        reviews: 70,
        citations: 60,
        websiteOptimization: 70,
      },
      recommendations: ["Add client testimonials", "Optimize for tax season", "Improve site structure"],
    },
  },
  {
    id: "27",
    businessName: "Speedy Auto Repair",
    category: "Auto Mechanic",
    phone: "(512) 789-0123",
    address: "789 Mechanic Row, Austin, TX 78708",
    leadScore: 88,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 45,
      factors: {
        googleMyBusiness: 80,
        localKeywords: 30,
        reviews: 60,
        citations: 35,
        websiteOptimization: 0,
      },
      recommendations: ["Build a service website", "Target auto repair keywords", "Add service descriptions"],
    },
  },
  {
    id: "28",
    businessName: "Petals & Stems Florist",
    category: "Florist",
    website: "https://petalsandstems.com",
    phone: "(512) 890-1234",
    email: "orders@petalsandstems.com",
    address: "321 Flower Ave, Austin, TX 78709",
    lighthouseScore: 74,
    leadScore: 71,
    leadType: "medium",
    source: "google-search",
    googleSearchRanking: 3,
    searchSnippet: {
      title: "Petals & Stems Florist - Fresh Flowers & Arrangements",
      description: "Beautiful fresh flower arrangements for all occasions. Same-day delivery available.",
      url: "https://petalsandstems.com",
      displayUrl: "petalsandstems.com",
    },
    localSEOScore: {
      overallScore: 73,
      factors: {
        googleMyBusiness: 85,
        localKeywords: 70,
        reviews: 75,
        citations: 65,
        websiteOptimization: 75,
      },
      recommendations: ["Add online ordering", "Optimize for wedding flowers", "Improve mobile experience"],
    },
  },
  {
    id: "29",
    businessName: "Lens & Light Photography",
    category: "Photographer",
    phone: "(512) 901-2345",
    address: "654 Photo Plaza, Austin, TX 78710",
    leadScore: 85,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 48,
      factors: {
        googleMyBusiness: 75,
        localKeywords: 40,
        reviews: 65,
        citations: 35,
        websiteOptimization: 0,
      },
      recommendations: ["Create a portfolio website", "Target event photography", "Build photography citations"],
    },
  },
  {
    id: "30",
    businessName: "Premier Construction Group",
    category: "Contractor",
    website: "https://premierconstructiongroup.com",
    phone: "(512) 012-3456",
    email: "info@premierconstructiongroup.com",
    address: "987 Builder Blvd, Austin, TX 78711",
    lighthouseScore: 58,
    leadScore: 77,
    leadType: "medium",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 5,
    searchSnippet: {
      title: "Premier Construction Group - Home Remodeling Experts",
      description: "Complete home remodeling and construction services. Licensed, bonded, and insured contractors.",
      url: "https://premierconstructiongroup.com",
      displayUrl: "premierconstructiongroup.com",
    },
    localSEOScore: {
      overallScore: 64,
      factors: {
        googleMyBusiness: 75,
        localKeywords: 60,
        reviews: 70,
        citations: 55,
        websiteOptimization: 60,
      },
      recommendations: ["Add project gallery", "Optimize for home renovation", "Improve site speed"],
    },
  },
  {
    id: "31",
    businessName: "Boston Bagel Company",
    category: "Bakery",
    phone: "(617) 123-4567",
    address: "123 Bagel Street, Boston, MA 02101",
    leadScore: 90,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 42,
      factors: {
        googleMyBusiness: 80,
        localKeywords: 25,
        reviews: 65,
        citations: 35,
        websiteOptimization: 0,
      },
      recommendations: ["Create an online ordering website", "Target breakfast keywords", "Build food citations"],
    },
  },
  {
    id: "32",
    businessName: "Harbor View Dental",
    category: "Dentist",
    website: "https://harborviewdental.com",
    phone: "(617) 234-5678",
    address: "456 Harbor Road, Boston, MA 02102",
    lighthouseScore: 39,
    leadScore: 80,
    leadType: "good",
    source: "google-search",
    googleSearchRanking: 6,
    searchSnippet: {
      title: "Harbor View Dental - Cosmetic & General Dentistry",
      description: "Modern dental practice offering cosmetic and general dentistry services with harbor views.",
      url: "https://harborviewdental.com",
      displayUrl: "harborviewdental.com",
    },
    localSEOScore: {
      overallScore: 59,
      factors: {
        googleMyBusiness: 70,
        localKeywords: 55,
        reviews: 65,
        citations: 50,
        websiteOptimization: 40,
      },
      recommendations: ["Improve website performance", "Add patient testimonials", "Optimize for cosmetic dentistry"],
    },
  },
  {
    id: "33",
    businessName: "North End Trattoria",
    category: "Restaurant",
    website: "https://northendtrattoria.com",
    phone: "(617) 345-6789",
    email: "reservations@northendtrattoria.com",
    address: "789 Hanover St, Boston, MA 02103",
    lighthouseScore: 81,
    leadScore: 56,
    leadType: "poor",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 1,
    searchSnippet: {
      title: "North End Trattoria - Authentic Italian Dining",
      description: "Traditional Italian cuisine in Boston's historic North End. Reservations recommended.",
      url: "https://northendtrattoria.com",
      displayUrl: "northendtrattoria.com",
    },
    localSEOScore: {
      overallScore: 84,
      factors: {
        googleMyBusiness: 90,
        localKeywords: 85,
        reviews: 85,
        citations: 80,
        websiteOptimization: 85,
      },
      recommendations: ["Maintain excellent performance", "Add online reservations", "Expand menu content"],
    },
  },
  {
    id: "34",
    businessName: "Beacon Hill Hair Design",
    category: "Hair Salon",
    website: "https://beaconhillhair.com",
    address: "321 Charles St, Boston, MA 02104",
    lighthouseScore: 52,
    leadScore: 68,
    leadType: "medium",
    source: "google-search",
    googleSearchRanking: 9,
    searchSnippet: {
      title: "Beacon Hill Hair Design - Upscale Hair Salon",
      description: "Upscale hair salon in historic Beacon Hill. Specializing in cuts, color, and styling.",
      url: "https://beaconhillhair.com",
      displayUrl: "beaconhillhair.com",
    },
    localSEOScore: {
      overallScore: 63,
      factors: {
        googleMyBusiness: 70,
        localKeywords: 60,
        reviews: 65,
        citations: 55,
        websiteOptimization: 55,
      },
      recommendations: ["Improve website speed", "Add online booking", "Showcase hair portfolio"],
    },
  },
  {
    id: "35",
    businessName: "Back Bay Fitness",
    category: "Gym",
    phone: "(617) 456-7890",
    address: "654 Newbury St, Boston, MA 02105",
    leadScore: 83,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 46,
      factors: {
        googleMyBusiness: 80,
        localKeywords: 35,
        reviews: 60,
        citations: 40,
        websiteOptimization: 0,
      },
      recommendations: ["Build a membership website", "Target fitness keywords", "Add class schedules online"],
    },
  },
  {
    id: "36",
    businessName: "Boston Bay Plumbing",
    category: "Plumber",
    website: "https://bostonbayplumbing.com",
    phone: "(617) 567-8901",
    email: "emergency@bostonbayplumbing.com",
    address: "987 Water St, Boston, MA 02106",
    lighthouseScore: 44,
    leadScore: 82,
    leadType: "good",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 3,
    searchSnippet: {
      title: "Boston Bay Plumbing - 24/7 Emergency Service",
      description: "Professional plumbing services with 24/7 emergency response. Licensed and insured plumbers.",
      url: "https://bostonbayplumbing.com",
      displayUrl: "bostonbayplumbing.com",
    },
    localSEOScore: {
      overallScore: 61,
      factors: {
        googleMyBusiness: 75,
        localKeywords: 60,
        reviews: 65,
        citations: 50,
        websiteOptimization: 45,
      },
      recommendations: ["Improve website performance", "Add service area pages", "Build plumbing citations"],
    },
  },
  {
    id: "37",
    businessName: "Commonwealth Legal Services",
    category: "Lawyer",
    phone: "(617) 678-9012",
    address: "432 State St, Boston, MA 02107",
    leadScore: 94,
    leadType: "excellent",
    source: "google-maps",
    googleMapsListing: true,
    localSEOScore: {
      overallScore: 40,
      factors: {
        googleMyBusiness: 75,
        localKeywords: 25,
        reviews: 55,
        citations: 30,
        websiteOptimization: 0,
      },
      recommendations: [
        "Create a professional law website",
        "Target legal practice keywords",
        "Build legal directories",
      ],
    },
  },
  {
    id: "38",
    businessName: "Precision Tax Services",
    category: "Accountant",
    website: "https://precisiontaxservices.com",
    phone: "(617) 789-0123",
    email: "info@precisiontaxservices.com",
    address: "765 Financial Ave, Boston, MA 02108",
    lighthouseScore: 71,
    leadScore: 74,
    leadType: "medium",
    source: "google-search",
    googleSearchRanking: 4,
    searchSnippet: {
      title: "Precision Tax Services - Professional Tax Preparation",
      description: "Expert tax preparation and accounting services for individuals and businesses in Boston.",
      url: "https://precisiontaxservices.com",
      displayUrl: "precisiontaxservices.com",
    },
    localSEOScore: {
      overallScore: 72,
      factors: {
        googleMyBusiness: 80,
        localKeywords: 70,
        reviews: 75,
        citations: 65,
        websiteOptimization: 75,
      },
      recommendations: ["Add tax calculator tools", "Optimize for tax season", "Improve local content"],
    },
  },
]

export const mockTableLeads: LeadTableItem[] = [
  {
    id: "1",
    businessName: "Sweet Dreams Bakery",
    category: "Bakery",
    phone: "(555) 123-4567",
    email: "info@sweetdreamsbakery.com",
    address: "123 Main St, Atlanta, GA 30309",
    leadScore: 95,
    leadType: "excellent",
    isInZoho: true,
    dateAdded: "2024-01-15",
    city: "Atlanta",
    state: "GA",
    source: "google-maps",
    googleMapsListing: true,
  },
  {
    id: "2",
    businessName: "Downtown Dental Care",
    category: "Dentist",
    website: "https://downtowndental.com",
    phone: "(555) 987-6543",
    address: "456 Oak Ave, Atlanta, GA 30308",
    lighthouseScore: 35,
    leadScore: 82,
    leadType: "good",
    isInZoho: false,
    dateAdded: "2024-01-14",
    city: "Atlanta",
    state: "GA",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 3,
  },
  {
    id: "3",
    businessName: "Bella Vista Restaurant",
    category: "Restaurant",
    website: "https://bellavista.com",
    phone: "(555) 456-7890",
    email: "contact@bellavista.com",
    address: "789 Pine St, Atlanta, GA 30307",
    lighthouseScore: 65,
    leadScore: 71,
    leadType: "medium",
    isInZoho: true,
    dateAdded: "2024-01-13",
    city: "Atlanta",
    state: "GA",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 1,
  },
  {
    id: "4",
    businessName: "Elite Hair Studio",
    category: "Hair Salon",
    website: "https://elitehairstudio.com",
    phone: "(555) 321-0987",
    address: "321 Elm St, Atlanta, GA 30306",
    lighthouseScore: 88,
    leadScore: 45,
    leadType: "poor",
    isInZoho: false,
    dateAdded: "2024-01-12",
    city: "Atlanta",
    state: "GA",
    source: "google-maps",
    googleMapsListing: true,
  },
  {
    id: "5",
    businessName: "City Fitness Center",
    category: "Gym",
    address: "654 Maple Ave, Atlanta, GA 30305",
    leadScore: 25,
    leadType: "research-needed",
    isInZoho: false,
    dateAdded: "2024-01-11",
    city: "Atlanta",
    state: "GA",
    source: "google-maps",
    googleMapsListing: true,
  },
  {
    id: "6",
    businessName: "Perfect Plumbing Solutions",
    category: "Plumber",
    phone: "(555) 789-0123",
    address: "987 Water St, Atlanta, GA 30304",
    leadScore: 88,
    leadType: "excellent",
    isInZoho: true,
    dateAdded: "2024-01-10",
    city: "Atlanta",
    state: "GA",
    source: "google-maps",
    googleMapsListing: true,
  },
  {
    id: "7",
    businessName: "Atlanta Artisan Bakery",
    category: "Bakery",
    website: "https://atlantaartisan.com",
    phone: "(555) 111-2222",
    email: "hello@atlantaartisan.com",
    address: "555 Creative St, Atlanta, GA 30310",
    lighthouseScore: 72,
    leadScore: 78,
    leadType: "medium",
    isInZoho: false,
    dateAdded: "2024-01-09",
    city: "Atlanta",
    state: "GA",
    source: "google-search",
    googleSearchRanking: 2,
  },
  {
    id: "8",
    businessName: "Neighborhood Baking Co",
    category: "Bakery",
    website: "https://neighborhoodbaking.com",
    address: "777 Community Ave, Atlanta, GA 30311",
    lighthouseScore: 45,
    leadScore: 65,
    leadType: "good",
    isInZoho: false,
    dateAdded: "2024-01-08",
    city: "Atlanta",
    state: "GA",
    source: "google-search",
    googleSearchRanking: 5,
  },
  // Add more table leads based on the new mock leads
  {
    id: "9",
    businessName: "Sunrise Dental Group",
    category: "Dentist",
    phone: "(555) 234-5678",
    email: "appointments@sunrisedental.com",
    address: "1234 Peachtree St, Atlanta, GA 30309",
    leadScore: 92,
    leadType: "excellent",
    isInZoho: false,
    dateAdded: "2024-01-07",
    city: "Atlanta",
    state: "GA",
    source: "google-maps",
    googleMapsListing: true,
  },
  {
    id: "10",
    businessName: "The Burger Joint",
    category: "Restaurant",
    website: "https://burgerjoint.com",
    phone: "(555) 345-6789",
    address: "567 Broad St, Atlanta, GA 30308",
    lighthouseScore: 38,
    leadScore: 79,
    leadType: "good",
    isInZoho: true,
    dateAdded: "2024-01-06",
    city: "Atlanta",
    state: "GA",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 4,
  },
  {
    id: "20",
    businessName: "Fresh Bites Cafe",
    category: "Restaurant",
    website: "https://freshbitescafe.com",
    address: "321 Coffee St, Austin, TX 78701",
    lighthouseScore: 43,
    leadScore: 67,
    leadType: "good",
    isInZoho: false,
    dateAdded: "2024-01-05",
    city: "Austin",
    state: "TX",
    source: "google-search",
    googleSearchRanking: 7,
  },
  {
    id: "21",
    businessName: "Austin Family Dentistry",
    category: "Dentist",
    website: "https://austinfamilydentistry.com",
    phone: "(512) 345-6789",
    email: "info@austinfamilydentistry.com",
    address: "654 Dental Drive, Austin, TX 78702",
    lighthouseScore: 89,
    leadScore: 52,
    leadType: "poor",
    isInZoho: true,
    dateAdded: "2024-01-04",
    city: "Austin",
    state: "TX",
    source: "both",
    googleMapsListing: true,
    googleSearchRanking: 1,
  },
  {
    id: "31",
    businessName: "Boston Bagel Company",
    category: "Bakery",
    phone: "(617) 123-4567",
    address: "123 Bagel Street, Boston, MA 02101",
    leadScore: 90,
    leadType: "excellent",
    isInZoho: false,
    dateAdded: "2024-01-03",
    city: "Boston",
    state: "MA",
    source: "google-maps",
    googleMapsListing: true,
  },
  {
    id: "32",
    businessName: "Harbor View Dental",
    category: "Dentist",
    website: "https://harborviewdental.com",
    phone: "(617) 234-5678",
    address: "456 Harbor Road, Boston, MA 02102",
    lighthouseScore: 39,
    leadScore: 80,
    leadType: "good",
    isInZoho: false,
    dateAdded: "2024-01-02",
    city: "Boston",
    state: "MA",
    source: "google-search",
    googleSearchRanking: 6,
  },
]

export const mockSearchResults: SearchResult[] = [
  {
    id: "1",
    searchParams: {
      businessType: "bakery",
      locations: ["atlanta", "austin"],
      numberOfBusinesses: 50,
      includeGoogleSearch: true,
      customSearchQuery: "artisan bakery atlanta",
      includeCompetitorAnalysis: true,
      includeTrendAnalysis: true,
    },
    leads: mockLeads,
    date: "2024-01-15",
    totalLeads: mockLeads.length,
    trendData: mockTrendData,
    competitorAnalysis: mockCompetitorAnalysis,
  },
  {
    id: "2",
    searchParams: {
      businessType: "dentist",
      locations: ["chicago", "denver"],
      numberOfBusinesses: 25,
      includeGoogleSearch: false,
      includeCompetitorAnalysis: false,
      includeTrendAnalysis: false,
    },
    leads: mockLeads.slice(0, 15),
    date: "2024-01-10",
    totalLeads: 15,
  },
]
